### PR TITLE
CMake: Add option to use bundled libusb library

### LINKED ISSUE #154: android-tools 35.0.2 requires new unreleased libusb changes
android-tools 35.0.2 fails to compile with libusb 1.0.27.

```
android-tools/vendor/adb/client/usb_libusb.cpp:539:46: error: ‘libusb_ssplus_usb_device_capability_descriptor’ has not been declared
  539 |     static uint64_t ExtractMaxSuperSpeedPlus(libusb_ssplus_usb_device_capability_descriptor* cap) {
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
android-tools/vendor/adb/client/usb_libusb.cpp: In static member function ‘static uint64_t
```

The above code was added in this adb commit https://android.googlesource.com/platform/packages/modules/adb.git/+/bb1d542466bfe7675022bec7345cbfdad0354d84%5E%21/

It depends on the this libusb commit https://github.com/libusb/libusb/commit/f00f06e9ebfcb5673c636e75d1f3d06375eccf03

What should be done to fix the issue? Possible solution:
1. Do not update android-tools until new libusb version is released.
2. Add libusb from googlesource in vendor.
3. Revert the commit which added new feature in adb repository.

(I prefer no.2)

@omasanori @Arnavion

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes #154

### CODE REVIEW

**Review by anatol — APPROVED** [review]
Fantastic! Thank you.

**Comment by Biswa96** [comment]
The previous iteration was incorrect. I did not notice the patch to include libusb-1.0 directory.
