### PR TITLE
Update to platform-tools-31.0.2

### LINKED ISSUE #28: The disconnected/rebootable device does not disconnect and remains in the active list (no control of the "offline" status)
Hello. Thank you very much for your work, it is very necessary and useful. I really need your advice on the following issue...  
I'm testing `android-tools v31.0.0p1` on emulators vv5.1/9.0 from: https://osdn.net/projects/android-x86/releases

> adb connect 192.168.0.80
connected to 192.168.0.80:5555
> adb devices
List of devices attached
192.168.0.80:5555	device

> adb shell reboot -p
... and here it continues to hang, and meanwhile the device is already turned off and, accordingly, does not accept any commands.

Tracking the `offline` status does not work when the device is rebooted or disconnected. Let me remind you that the normal shutdown/reboot of the device takes place in several stages...

For example - normal Shutdown:
--
1. command:  `adb shell reboot -p`
2. Turning off the device
3. The adb server shows the status "offline" (`adb devices`)
4. **After 1-2 minutes, the device that is already turned off leaves the list of connected devices**

In versions 29.0.6, 30.0.5p1 & 31.0.0p1 (I didn't check the others) the disconnected device is permanently connected even after it is disconnected. Is this a bug?

I can't test it on a real device, there is no smartphone.
I apologize for my poor English, I communicate through an online translator.

p.s. for easy and quick control of the device behavior, you can use my `ADBManager`: https://github.com/AKotov-dev/adbmanager if compatible for you. It is under development, but it will speed up the process of testing android-tools in general.

Sincerely,
Alex

### PR DESCRIPTION
**Pull request by nmeum**
To-Do:

* [x] Test with clang
* [ ] Test with glibc-based System
* [ ] Make sure it builds with GCC 11.X before making a new release (see #26)

Fixes #28

### CODE REVIEW

File: patches/incremental_delivery/0001-Add-prototype-for-opreator-to-iterator.patch [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+	/usr/include/c++/10.3.1/bits/stl_algo.h:2046:32:   required from 'constexpr _FIter std::lower_bound(_FIter, _FIter, const _Tp&, _Compare) [with _FIter = android::incfs::map_ptr<android::ResTable_sparseTypeEntry, false>::const_iterator; _Tp = short unsigned int; _Compare = android::LoadedPackage::GetEntryOffset(android::incfs::verified_map_ptr<android::ResTable_type>, uint16_t)::<lambda(const android::incfs::map_ptr<android::ResTable_sparseTypeEntry, false>&, uint16_t)>]'
+	/home/soeren/src/android-tools/vendor/base/libs/androidfw/LoadedArsc.cpp:276:6:   required from here
+	/usr/include/c++/10.3.1/bits/stl_iterator_base_funcs.h:183:2: error: no match for 'operator--' (operand type is 'android::incfs::map_ptr<android::ResTable_sparseTypeEntry, false>::const_iterator')
+	  183 |  --__i;
+	      |  ^~~~~
```
Comment (nmeum) [inline patches/incremental_delivery/0001-Add-prototype-for-opreator-to-iterator.patch:19]: No idea what this is about, if anyone has a better idea on how to fix this. Let me know.

Comment (AKotov-dev) [reply patches/incremental_delivery/0001-Add-prototype-for-opreator-to-iterator.patch:19]: Hello, **nmeum**. Thank you so much for the update v31.0.2

I added a package fmt-devel (urpmi --auto "pkgconfig(fmt)" - for Mageia Linux only)

mkdir ./111 && cd ./111
git clone --recurse-submodules --depth=1 --branch=platform-tools-31.0.2 https://github.com/nmeum/android-tools.git

cd ./android-tools
mkdir ./build && cd ./build

cmake ..
make

cd ./vendor

./adb version
Android Debug Bridge version 1.0.41
Version 31.0.0p1-android-tools

The android-tool version is still 31.0.0p1. :( I checked - all the patches are applied correctly. In any case, he told me that he was working with v31.0.2 and everything was assembled without errors. In addition, I will leave the address for the already patched archive android-tools-31.0.2.tar.xz: https://cloud.mail.ru/public/gKRe/PJ9JKKZ11

The testing result: the version of android-tools is still 31.0.0p1 and, accordingly, the "adb" problem "Reduce TCP keepalive interval" remains.

I still have little experience with GitHub, maybe I cloned the branch incorrectly? :)

Regarding the error you described above... Unfortunately, I do not program in C++, but I repeat that the build was done using all the patches and without errors. Perhaps I'm not talking about what you need at all, but in the link above, in addition to *.tar.xz, there is also a log file. If I have said too much, please do not judge me too harshly. :)

With respect,
Alex

Comment (nmeum) [reply patches/incremental_delivery/0001-Add-prototype-for-opreator-to-iterator.patch:19]: > The android-tool version is still 31.0.0p1.

Yes, didn't update the version string yet. Should be fixed in 111415ed4e71012cca364d6f987726f0407cef92

Comment (nmeum) [reply patches/incremental_delivery/0001-Add-prototype-for-opreator-to-iterator.patch:19]: Do you happen to know which upstream commit fixes your TCP timeout issue?

**Comment by nmeum** [comment]
Looks like I checked out the wrong tag for some submodules, will fix that later.

**Comment by nmeum** [comment]
@AKotov-dev should be fixed now (hopefully) :)

**Comment by AKotov-dev** [comment]
@nmeum
```
mkdir ./build && cd ./build

# Attempt-1
cmake ..
...
...
-- Applying patches for: base
Applying: LoadedArsc: un-const T in std::vector<T>
Applying: PosixUtils: don't use reserved name std{out,err} for variables
Applying: AssetManager2: Align creation of FindEntryResult with declaration
-- Applying patches for: core
error: error applying changes: llkd/include/llkd.h:63
error: llkd/include/llkd.h: failed to apply patch
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Applying: Fix inclusion of stdatomic.h with g++
Applying: group_member is a nonstandard GNU extension
Applying: socket.h: include sys/select.h for fd_set used in socket.cpp
Applying: fastboot: make mke2fs_path configurable
Applying: libcutils: include sys/select.h for timeval
Applying: Don't include version.h
Applying: Include cstring in various file missing it
Applying: Vector: don't assign to const object
Applying: Don't use the internal glibc header sys/cdefs.h
Error applying changes to 0009 Don't use the internal glibc header sys/cdefs.h
When you resolve this issue, run «git am --continue».
If you want to skip this patch, then run «git am --skip».
To go back to the previous branch and stop applying the changes, run «git am --abort».
CMake Error at vendor/CMakeLists.txt:30 (message):
  Couldn't apply patches for core

-- Configuring incomplete, errors occurred!
See also "/111/android-tools-31.0.2/android-tools/build/CMakeFiles/CMakeOutput.log".

# Attempt-2
cmake ..
-- Applying patches for: adb
Applying: Don't use the internal glibc header sys/cdefs.h
Applying: adb: disable mdns transport support
Applying: fdevent: missing atomic include
Applying: Define clang-only nullability specifiers when __clang__ is not defined
Applying: Include libusb-1.0/libusb.h instead of libusb/libusb.h
Applying: Include string.h in various file missing it
Applying: adb.cpp: fix warning regarding execl(3) invocation
Applying: usb_linux.cpp: include sys/sysmacros.h for minor/major
Applying: adb: Reduce fallback size for _SC_GETPW_R_SIZE_MAX
Applying: sysdeps: don't over eager constexpr
Applying: Don't include version.h
Applying: Include cstring in various file missing it
Applying: adb: disable fastdeploy support
Applying: include climits where necessary for INT_MAX
Applying: types.h: Fix ambiguous reference to weak_ptr
Applying: adb: disable mDNS
Applying: adb_wifi: remove mDNS
Applying: pairing_auth: include <cstring> for memcpy
Applying: adb_mdns: Don't use _Nonnull
-- Applying patches for: base
Applying: LoadedArsc: un-const T in std::vector<T>
Applying: PosixUtils: don't use reserved name std{out,err} for variables
Applying: AssetManager2: Align creation of FindEntryResult with declaration
-- Applying patches for: core
fatal: previous rebase directory /111/android-tools-31.0.2/android-tools/.git/modules/core/rebase-apply still exists, but give to mbox.

CMake Error at vendor/CMakeLists.txt:30 (message):
  Couldn't apply patches for core
```
For the purity of the experiment, I tried downloading/cloning twice. Output of `cmake ..` Additionally, I attach the file `CMakeOutput.log`: https://cloud.mail.ru/public/gKRe/PJ9JKKZ11

**nmeum**, I feel that the truth is somewhere near. :)

**Comment by nmeum** [comment]
Looks like some submodules are in a bad state (you can check them individually with `git status`). In the main repo non of the submodules should be marked as modified/changed in the `git status` output, you can also reset them with `git submodule update --init`.

Have you tried a clean build with a clean checkout? For example:

```
cd /tmp
git clone --recursive -b platform-tools-31.0.2 https://github.com/nmeum/android-tools
cd android-tools
mkdir build
cd build
cmake ..
make
```

**Comment by AKotov-dev** [comment]
Every new build is completely new. I always completely delete the directory `rm -rf ./android-tools` with all the contents and recreate/clone everything again. Now I repeated everything from the beginning to the end for the third time - the result is the same.

Total downloaded/cloned ~7GB...
```
# After the end of cloning:
Defining changes: 100% (17792/17792), done.
Submodule on the way «vendor/adb»: state selected «93acca4dfa6f59e85f86442a160e57e0d3208176»
Submodule on the way «vendor/avb»: state selected «f2cc0562cd31bbc584e3bd61d80c082b31520ec1»
Submodule on the way «vendor/base»: state selected «9a460c961bb1e6e15b886f1d48681ca159c2de15»
Submodule on the way «vendor/boringssl»: state selected «c1e156ae16fa8b61af9b5d2b74e59d3f86e141be»
Submodule on the way «vendor/core»: state selected «fc1e6adc6f9d552cb2305a22d9d4de39af0038d7»
Submodule on the way «vendor/e2fsprogs»: state selected «584ac7d2ccbd9760e83af43c2cdb9bf495404c1f»
Submodule on the way «vendor/extras»: state selected «f79ba08eb13c46466b1b44d76ca97e530d06261d»
Submodule on the way «vendor/f2fs-tools»: state selected «df24542a7c67c8d09d2b0c946028af11f8afa557»
Submodule on the way «vendor/incremental_delivery»: state selected «d8df24315af647a3a97bc6544107cfcfc1a31866»
Submodule on the way «vendor/libbase»: state selected «18f8b14dac2bacf3a3cdc7d9e54dbd2888043e0d»
Submodule on the way «vendor/libziparchive»: state selected «b97a38bd72a1534f99d08a48fc92606f8e67f4f2»
Submodule on the way «vendor/logging»: state selected «26849884bcd3002c4cf74a819f42ace46ad7a6c5»
Submodule on the way «vendor/mkbootimg»: state selected «b6ef0d18503fc92bf92cb07400739ec158e6c1a2»
Submodule on the way «vendor/native»: state selected «a4a1fd3132e8ad535d091bfc4f83742d39eb3030»
Submodule on the way «vendor/selinux»: state selected «e3153f6df50bb06cb215be672b9043e33f638152»
```
```
cd ./android-tools
git submodule update --init

mkdir ./build && cd ./build && cmake ..

-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Perl: /usr/bin/perl (found version "5.32.1") 
-- Checking for module 'libunwind-generic'
--   Found libunwind-generic, version 1.5.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Applying patches for: adb
Applying: Don't use the internal glibc header sys/cdefs.h
Applying: adb: disable mdns transport support
Applying: fdevent: missing atomic include
Applying: Define clang-only nullability specifiers when __clang__ is not defined
Applying: Include libusb-1.0/libusb.h instead of libusb/libusb.h
Applying: Include string.h in various file missing it
Applying: adb.cpp: fix warning regarding execl(3) invocation
Applying: usb_linux.cpp: include sys/sysmacros.h for minor/major
Applying: adb: Reduce fallback size for _SC_GETPW_R_SIZE_MAX
Applying: sysdeps: don't over eager constexpr
Applying: Don't include version.h
Applying: Include cstring in various file missing it
Applying: adb: disable fastdeploy support
Applying: include climits where necessary for INT_MAX
Applying: types.h: Fix ambiguous reference to weak_ptr
Applying: adb: disable mDNS
Applying: adb_wifi: remove mDNS
Applying: pairing_auth: include <cstring> for memcpy
Applying: adb_mdns: Don't use _Nonnull
-- Applying patches for: base
Applying: LoadedArsc: un-const T in std::vector<T>
Applying: PosixUtils: don't use reserved name std{out,err} for variables
Applying: AssetManager2: Align creation of FindEntryResult with declaration
-- Applying patches for: core
error: error applying changes: llkd/include/llkd.h:63
error: llkd/include/llkd.h: failed to apply patch
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Applying: Fix inclusion of stdatomic.h with g++
Applying: group_member is a nonstandard GNU extension
Applying: socket.h: include sys/select.h for fd_set used in socket.cpp
Applying: fastboot: make mke2fs_path configurable
Applying: libcutils: include sys/select.h for timeval
Applying: Don't include version.h
Applying: Include cstring in various file missing it
Applying: Vector: don't assign to const object
Applying: Don't use the internal glibc header sys/cdefs.h
Error applying changes to 0009 Don't use the internal glibc header sys/cdefs.h
When you resolve this issue, run «git am --continue».
If you want to skip this patch, then run «git am --skip».
To go back to the previous branch and stop applying the changes, run «git am --abort».
CMake Error at vendor/CMakeLists.txt:30 (message):
  Couldn't apply patches for core


-- Configuring incomplete, errors occurred!
See also "/222/android-tools/build/CMakeFiles/CMakeOutput.log".
```
And here it turns out some bad thing...

**Comment by nmeum** [comment]
Can you try again? :)

**Comment by AKotov-dev** [comment]
@nmeum 
Hooray, it's working! :) Now everything is assembled without errors and the "offline" state is also tracked correctly. That was cool! Thank you very much for your work. I look forward to the release of v31.0.2 to please the maintainers, to get the new package as soon as possible.

Sincerely, Alex

File: patches/incremental_delivery/0001-Add-prototype-for-opreator-to-iterator.patch (hunk 1 above)
Comment (nmeum) [inline patches/incremental_delivery/0001-Add-prototype-for-opreator-to-iterator.patch:19]: @anatol any idea what this might be about?

File: CMakeLists.txt [hunk 2]
```diff
@@ -19,7 +19,7 @@ set(ANDROID_MKE2FS_NAME "mke2fs.android")
 
 # Version of android-tools and the version of boringssl being used.
 # See: https://android.googlesource.com/platform/external/boringssl/+/platform-tools-${ANDROID_VERSION}/BORINGSSL_REVISION
-set(ANDROID_VERSION 31.0.0p1)
+set(ANDROID_VERSION 31.0.2)
 set(BORINGSSL_VERSION c1e156ae16fa8b61af9b5d2b74e59d3f86e141be)
```
Comment (vanaf) [inline CMakeLists.txt:23]: Should be ae2bb641735447496bed334c495e4868b981fe32 according to link above.

Comment (nmeum) [reply CMakeLists.txt]: Indeed, thanks for pointing this out. Should be fixed now.,

**Comment by nmeum** [comment]
Did tests with clang, will do further tests before doing the next release.
